"""Package management: install, update (with schema-compatibility analysis), lock, publish, migrate.

Nothing changes project knowledge silently:
* `update` first compiles the workspace against the candidate version in memory and reports breaking
  type changes, the objects that would break, and which migrations the package ships.
* Migrations are dry-run by default; `apply` rewrites files only with approval, and the result is
  compiled again so any remaining diagnostics are visible.

migrations/<type>-<from>-to-<to>.migration.yaml (shipped by the package that owns the type):
    type: decision
    from: 1
    to: 2
    ops:
      - rename_field: {from: chosen, to: selected}
      - map_values: {field: status, map: {approved: accepted}}
      - set_default: {field: owner, value: unassigned}
      - remove_field: legacy
"""
from __future__ import annotations

import shutil
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from lif.knowledge import parse as P
from lif.knowledge.compiler import Compiler
from lif.knowledge.repo import Dependency, Repo, RepoError, Workspace, satisfies, tree_hash, vparse
from lif.knowledge.store import Store
from lif.knowledge.types import TypeDef, type_changes

if TYPE_CHECKING:
    from lif.knowledge.ops import Knowledge


class ApprovalRequired(Exception):
    pass


def _types(repo: Repo) -> dict[str, TypeDef]:
    out = {}
    for f in repo.type_files():
        raw = yaml.safe_load(f.read_text()) or {}
        t = TypeDef.from_yaml(raw, repo.name, str(f))
        out[t.name] = t
    return out


def _skills(repo: Repo) -> dict[str, int]:
    out = {}
    for d in repo.skills():
        fm, _, _ = P.split_front_matter((d / "SKILL.md").read_text())
        out[d.name] = int(((yaml.safe_load(fm) or {}) if fm else {}).get("version", 1))
    return out


# ── lock ─────────────────────────────────────────────────────────────────────

def lock(ws: Workspace, repo: Repo) -> dict:
    """Pin every package this repo reaches: version, content hash, type and skill versions."""
    pkgs: dict[str, Any] = {}
    queue = list(repo.dependencies)
    seen: set[str] = set()
    while queue:
        d = queue.pop(0)
        if d.name in seen or ws.repo(d.name) is None or ws.repo(d.name).source == "workspace":
            seen.add(d.name)
            continue
        seen.add(d.name)
        p = ws.packages[d.name]
        pkgs[d.name] = {"version": p.version, "hash": tree_hash(p.path),
                        "types": {n: t.version for n, t in sorted(_types(p).items())},
                        "skills": _skills(p),
                        "tools": sorted({t for s in p.skills() if (s / "tools.yaml").exists()
                                         for t in (yaml.safe_load((s / "tools.yaml").read_text()) or {}).get("tools", [])})}
        queue += p.dependencies
    data = {"lockfile": 1, "repo": repo.name, "packages": dict(sorted(pkgs.items()))}
    repo.lock_path().write_text("# Generated by `knowledge lock`. Pins packages for reproducible agent work.\n" +
                                yaml.safe_dump(data, sort_keys=False))
    return data


# ── install / update ─────────────────────────────────────────────────────────

def install(kn: "Knowledge", repo_name: str, spec: str, approved: bool = False, force: bool = False) -> dict:
    name, _, constraint = spec.partition("@")
    repo = kn.ws.repo(repo_name)
    if repo is None or not repo.writable:
        raise RepoError(f"no writable repo '{repo_name}'")
    version = kn.ws.registry.best(name, constraint or "*")
    if version is None:
        raise RepoError(f"{spec}: no matching version in the registry ({kn.ws.registry.packages().get(name, [])})")
    if not approved:
        raise ApprovalRequired(f"installing {name}@{version} into {repo.name} needs approval "
                               f"(human: `knowledge package install {spec} --repo {repo.name} --yes`)")
    manifest_before = (repo.path / "repo.yaml").read_text()
    lock_before = repo.lock_path().read_text() if repo.lock_path().exists() else None
    errors_before = {d["message"] for d in kn.store.diagnostics("error")}
    repo.dependencies = [d for d in repo.dependencies if d.name != name] + [
        Dependency(name, constraint or f"^{'.'.join(version.split('.')[:2])}")]
    repo.save_manifest()
    if repo.lock_path().exists():
        repo.lock_path().unlink()                     # re-resolve, then pin
    ws = Workspace.open(kn.ws.root, registry=kn.ws.registry.root)
    lock(ws, ws.repo(repo.name))
    stats = kn.rebuild()
    new_errors = [d for d in kn.store.diagnostics("error") if d["message"] not in errors_before]
    if new_errors and not force:
        (repo.path / "repo.yaml").write_text(manifest_before)
        if lock_before is None:
            repo.lock_path().unlink(missing_ok=True)
        else:
            repo.lock_path().write_text(lock_before)
        kn.rebuild()
        raise RepoError(f"install rolled back: {len(new_errors)} new error(s): " +
                        "; ".join(d["message"] for d in new_errors[:5]))
    p = kn.ws.packages.get(name)
    return {"installed": name, "version": version, "repo": repo.name, "compile": stats,
            "exports": p.exports if p else {}, "skills": sorted(_skills(p)) if p else []}


def check_update(kn: "Knowledge", repo_name: str, name: str, to: str | None = None) -> dict:
    """Compatibility report for moving `name` to `to` (default: newest version in the registry)."""
    repo = kn.ws.repo(repo_name)
    cur = kn.ws.packages.get(name)
    if cur is None:
        raise RepoError(f"{name} is not a dependency of the workspace")
    target = to or kn.ws.registry.best(name, "*")
    if target is None:
        raise RepoError(f"{name}: nothing in the registry")
    cand = kn.ws.registry.load(name, target)
    dep = next((d for d in repo.dependencies if d.name == name), None)
    old_t, new_t = _types(cur), _types(cand)
    changes: dict[str, list[dict]] = {}
    for tn in sorted(set(old_t) | set(new_t)):
        if tn not in new_t:
            changes[tn] = [{"field": "", "change": "type removed", "breaking": True}]
        elif tn not in old_t:
            changes[tn] = [{"field": "", "change": "type added", "breaking": False}]
        else:
            ch = type_changes(old_t[tn], new_t[tn])
            if ch or old_t[tn].version != new_t[tn].version:
                changes[tn] = ch or [{"field": "", "change": f"version {old_t[tn].version} → {new_t[tn].version}",
                                      "breaking": False}]
    migrations = [m for m in load_migrations(cand) if m["type"] in old_t and
                  int(m["from"]) >= old_t[m["type"]].version and int(m["to"]) <= new_t.get(m["type"], old_t[m["type"]]).version]
    # what would break: compile the workspace against the candidate in memory
    before = _error_set(kn.store)
    ws = Workspace.open(kn.ws.root, registry=kn.ws.registry.root)
    ws.packages[name] = cand
    ws.problems = [p for p in ws.problems if name not in p["message"]]
    trial = Store(None)
    Compiler(ws, trial).compile()
    after = _error_set(trial)
    new_errors = [dict(zip(("code", "key", "message"), e)) for e in sorted(after - before)]
    breaking = any(c["breaking"] for cs in changes.values() for c in cs)
    major = vparse(target)[0] != vparse(cur.version)[0]
    return {"package": name, "from": cur.version, "to": target,
            "within_constraint": satisfies(target, dep.version if dep else "*"),
            "major": major, "breaking": breaking, "type_changes": changes,
            "migrations": [{k: m[k] for k in ("type", "from", "to", "file")} for m in migrations],
            "would_break": new_errors, "compatible": not new_errors,
            "advice": ("compatible: no existing object breaks" if not new_errors else
                       f"{len(new_errors)} object(s) would break" +
                       (f"; {len(migrations)} migration(s) available — run with --migrate" if migrations else
                        "; no migration shipped — fix objects or stay on " + cur.version))}


def _error_set(store: Store) -> set[tuple]:
    return {(d["code"], d["key"], d["message"]) for d in store.diagnostics("error")}


def update(kn: "Knowledge", repo_name: str, name: str, to: str | None = None, migrate: bool = False,
           approved: bool = False) -> dict:
    report = check_update(kn, repo_name, name, to)
    if not approved:
        report["applied"] = False
        report["approval"] = (f"package upgrades need approval (human: `knowledge package update {name} "
                              f"--repo {repo_name}{' --migrate' if migrate else ''} --yes`)")
        return report
    if report["would_break"] and not (migrate and report["migrations"]):
        raise RepoError(f"refusing: {report['advice']}")
    repo = kn.ws.repo(repo_name)
    if not report["within_constraint"]:
        for d in repo.dependencies:
            if d.name == name:
                d.version = f"^{'.'.join(report['to'].split('.')[:2])}"
        repo.save_manifest()
    lockdata = repo.read_lock()
    lockdata.setdefault("packages", {}).pop(name, None)
    repo.lock_path().write_text(yaml.safe_dump(lockdata, sort_keys=False))
    ws = Workspace.open(kn.ws.root, registry=kn.ws.registry.root)
    ws.packages[name] = kn.ws.registry.load(name, report["to"])
    lock(ws, ws.repo(repo_name))
    applied = []
    if migrate:
        cand = kn.ws.registry.load(name, report["to"])
        for m in load_migrations(cand):
            if any(m["file"] == x["file"] for x in report["migrations"]):
                applied.append(apply_migration(kn, m, approved=True))
    report.update(applied=True, migrations_applied=applied, compile=kn.rebuild(),
                  errors_after=[d["message"] for d in kn.store.diagnostics("error")][:20])
    return report


# ── migrations ───────────────────────────────────────────────────────────────

def load_migrations(repo: Repo) -> list[dict]:
    out = []
    for f in repo.glob("migrations", "*.migration.yaml"):
        raw = yaml.safe_load(f.read_text()) or {}
        raw["file"] = str(f)
        raw["package"] = repo.name
        out.append(raw)
    return sorted(out, key=lambda m: (m["type"], int(m["from"])))


def _rewrite(fields: dict, ops: list[dict]) -> dict:
    f = dict(fields)
    for op in ops:
        (kind, arg), = op.items()
        if kind == "rename_field" and arg["from"] in f:
            f[arg["to"]] = f.pop(arg["from"])
        elif kind == "map_values" and arg["field"] in f:
            mp, v = arg["map"], f[arg["field"]]
            f[arg["field"]] = [mp.get(x, x) for x in v] if isinstance(v, list) else mp.get(v, v)
        elif kind == "set_default":
            f.setdefault(arg["field"], arg["value"])
        elif kind == "remove_field":
            f.pop(arg if isinstance(arg, str) else arg["field"], None)
        elif kind == "wrap_list" and arg in f and not isinstance(f[arg], list):
            f[arg] = [f[arg]]
    return f


def plan_migration(kn: "Knowledge", m: dict) -> list[dict]:
    """Which files change and how (no writes)."""
    plan = []
    for o in kn.store.objects("type_name=? AND sub IS NULL AND source='workspace'", (m["type"],), limit=10 ** 6):
        path = Path(o["path"])
        fm, body, _ = P.split_front_matter(path.read_text())
        head = yaml.safe_load(fm) or {}
        new = _rewrite(head, m.get("ops") or [])
        if new != head:
            plan.append({"key": o["key"], "path": str(path), "before": head, "after": new,
                         "text": P.dump({k: v for k, v in new.items() if k not in ("type", "id")}, body,
                                        oid=new.get("id"), otype=new.get("type"))})
    return plan


def apply_migration(kn: "Knowledge", m: dict, approved: bool = False, dry_run: bool = False) -> dict:
    plan = plan_migration(kn, m)
    summary = {"migration": Path(m["file"]).name, "type": m["type"], "from": m["from"], "to": m["to"],
               "objects": [{"key": p["key"], "path": p["path"],
                            "changes": {k: {"from": p["before"].get(k), "to": p["after"].get(k)}
                                        for k in sorted(set(p["before"]) | set(p["after"]))
                                        if p["before"].get(k) != p["after"].get(k)}} for p in plan]}
    if dry_run or not approved:
        # diagnostics the migrated files would produce, compiled from a scratch copy
        with tempfile.TemporaryDirectory() as tmp:
            shutil.copytree(kn.ws.root, tmp, dirs_exist_ok=True,
                            ignore=shutil.ignore_patterns(".knowledge", ".git", "registry"))
            for p in plan:
                rel = Path(p["path"]).relative_to(kn.ws.root) if Path(p["path"]).is_relative_to(kn.ws.root) else None
                if rel is not None:
                    (Path(tmp) / rel).write_text(p["text"])
            ws = Workspace.open(tmp, registry=kn.ws.registry.root)
            trial = Store(None)
            Compiler(ws, trial).compile()
            summary["diagnostics_after"] = [{"code": d["code"], "key": d["key"], "message": d["message"]}
                                            for d in trial.diagnostics("error")
                                            if d["key"] and d["key"].split("^")[0].split("::")[-1] in
                                            {p["key"].split("::")[-1] for p in plan}]
        summary["applied"] = False
        if not approved and not dry_run:
            summary["approval"] = "schema migrations need approval (human: `knowledge migrate ... --apply --yes`)"
        return summary
    for p in plan:
        Path(p["path"]).write_text(p["text"])
    kn.rebuild()
    summary["applied"] = True
    summary["diagnostics_after"] = [d["message"] for d in kn.store.diagnostics("error")
                                    if d["key"] in {p["key"] for p in plan}]
    return summary


def publish(kn: "Knowledge", path: str | Path, approved: bool = False) -> dict:
    if not approved:
        raise ApprovalRequired("publishing a package needs approval (human: `knowledge package publish PATH --yes`)")
    r = kn.ws.registry.publish(Path(path))
    return {"published": r.name, "version": r.version, "path": str(r.path), "hash": tree_hash(r.path)}


def inspect(kn: "Knowledge", name: str, version: str | None = None) -> dict:
    version = version or kn.ws.registry.best(name, "*")
    if version is None:
        raise RepoError(f"no package {name}")
    p = kn.ws.registry.load(name, version)
    return {"name": p.name, "version": p.version, "description": p.description,
            "dependencies": [{"name": d.name, "version": d.version} for d in p.dependencies],
            "exports": p.exports, "types": {n: t.version for n, t in _types(p).items()}, "skills": _skills(p),
            "views": [f.name for f in p.glob("views", "*.view.yaml")],
            "migrations": [Path(m["file"]).name for m in load_migrations(p)],
            "versions": kn.ws.registry.packages().get(name, []), "hash": tree_hash(p.path),
            "used_by": [r.name for r in kn.ws.repos if any(d.name == name for d in r.dependencies)]}


def extract(kn: "Knowledge", repo_name: str, name: str, version: str, dst: str | Path, *,
            objects: list[str] | None = None, skills: list[str] | None = None, types: list[str] | None = None,
            views: list[str] | None = None, description: str = "", dependencies: list[dict] | None = None) -> dict:
    """Turn practices proven in a project into a package source tree (then `publish` it).

    Links to objects that stay behind in the project are de-linked to plain `repo::id` text (kept as
    provenance), because a package cannot depend on the project it came from."""
    import re
    repo = kn.ws.repo(repo_name)
    dst = Path(dst)
    if dst.exists():
        raise RepoError(f"{dst} exists")
    keys = [kn.graph.key(o, repo_name) for o in objects or []]
    ids = {kn.store.get(k)["id"] for k in keys} | set(skills or [])
    copied: list[str] = []
    markers: set[str] = set()

    def delink_md(text: str) -> str:
        """De-link, then move de-linked values out of front-matter fields into `provenance` (plain text)."""
        text = delink(text)
        fm, body, _ = P.split_front_matter(text)
        if fm is None:
            return text
        head = yaml.safe_load(fm) or {}
        prov = list(head.get("provenance") or [])
        for k, v in list(head.items()):
            if isinstance(v, list) and any(isinstance(x, str) and x in markers for x in v):
                prov += [x for x in v if isinstance(x, str) and x in markers]
                head[k] = [x for x in v if not (isinstance(x, str) and x in markers)] or None
            elif isinstance(v, str) and v in markers:
                prov.append(v)
                head[k] = None
        if prov:
            head["provenance"] = sorted(set(prov))
        head = {k: v for k, v in head.items() if v is not None}
        return P.dump({k: v for k, v in head.items() if k not in ("type", "id")}, body, oid=head.get("id"),
                      otype=head.get("type"))

    def delink(text: str) -> str:
        def sub(m: re.Match) -> str:
            target = m.group(1)
            ns, _, base = target.split("^")[0].rpartition("::")
            if (not ns and base in ids) or (ns and (kn.ws.repo(ns) is not None and kn.ws.repo(ns).source == "registry")):
                return m.group(0)                        # inside the package, or another package
            plain = target if ns else f"{repo_name}::{target}"
            markers.add(plain)
            return plain
        return re.sub(r"\[\[([^\]|]+)\]\]", sub, text)

    for k in keys:
        o = kn.store.get(k)
        folder = "methods" if o["type_name"] == "method" else "knowledge"
        out = dst / folder / Path(o["path"]).name
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(delink_md(Path(o["path"]).read_text()))
        copied.append(str(out))
    for s in skills or []:
        src = repo.path / "skills" / s
        shutil.copytree(src, dst / "skills" / s)
        for f in (dst / "skills" / s).rglob("*"):
            if f.is_file() and f.suffix in (".md", ".yaml") and "tests" not in f.parts:
                f.write_text(delink_md(f.read_text()) if f.suffix == ".md" else delink(f.read_text()))
        copied.append(str(dst / "skills" / s))
    for t in types or []:
        (dst / "types").mkdir(parents=True, exist_ok=True)
        shutil.copy(repo.path / "types" / f"{t}.type.yaml", dst / "types")
    for v in views or []:
        (dst / "views").mkdir(parents=True, exist_ok=True)
        shutil.copy(repo.path / "views" / f"{v}.view.yaml", dst / "views")
    deps = dependencies if dependencies is not None else [
        {"name": d.name, "version": d.version} for d in repo.dependencies if kn.ws.repo(d.name) and
        kn.ws.repo(d.name).source == "registry"]
    manifest = {"name": name, "version": version, "kind": "package",
                "description": description or f"Extracted from {repo_name}", "dependencies": deps,
                "exports": {"skills": list(skills or []), "types": list(types or []), "views": list(views or []),
                            "methods": [kn.store.get(k)["id"] for k in keys if kn.store.get(k)["type_name"] == "method"]},
                "extracted_from": {"repo": repo_name, "version": repo.version}}
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "repo.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False))
    return {"package": name, "version": version, "path": str(dst), "files": copied}


def test_types(kn: "Knowledge", name: str, version: str | None = None) -> dict:
    """Type tests for a package: tests/types/valid/*.md must compile without errors; each
    tests/types/invalid/<CODE>-*.md must produce diagnostic CODE (valid/ examples are in scope)."""
    version = version or kn.ws.registry.best(name, "*")
    pkg = kn.ws.registry.load(name, version)
    tdir = pkg.path / "tests" / "types"
    cases = []
    if not tdir.exists():
        return {"package": name, "version": version, "cases": [], "passed": True, "note": "no type tests"}
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "t").mkdir()
        (root / "t" / "repo.yaml").write_text(yaml.safe_dump({"name": "t", "kind": "project", "dependencies": [
            {"name": name, "version": version}]}))
        shutil.copytree(tdir / "valid", root / "t" / "valid") if (tdir / "valid").exists() else None
        shutil.copytree(tdir / "invalid", root / "t" / "invalid") if (tdir / "invalid").exists() else None
        (root / "workspace.yaml").write_text(yaml.safe_dump({"repos": ["t"]}))
        ws = Workspace.open(root, registry=kn.ws.registry.root)
        st = Store(None)
        Compiler(ws, st).compile()
        diags = st.diagnostics()
        for f in sorted((root / "t").rglob("*.md")):
            mine = [d for d in diags if d["path"] == str(f) and d["severity"] == "error"]
            if f.parent.name == "valid":
                cases.append({"case": f"valid/{f.name}", "ok": not mine, "errors": [d["message"] for d in mine]})
            else:
                code = f.name.split("-", 1)[0]
                cases.append({"case": f"invalid/{f.name}", "ok": any(d["code"] == code for d in mine),
                              "expected": code, "got": sorted({d["code"] for d in mine})})
    return {"package": name, "version": version, "cases": cases, "passed": all(c["ok"] for c in cases)}
