"""Ask and the command bar: /api/ai/* (threads, streaming messages, capabilities) and /api/command.

Spec §7–§11, §18–§21, §64, §67–§70.

Streaming. POST /api/ai/threads/{id}/messages answers with text/event-stream: `route` (as soon as the
gateway picks a model; an early one with just the mode so the screen isn't blank while a request
queues), `delta` (text), then `receipt` or `error`, then `done`. The gateway call runs in its own task
that does not depend on the browser: if the phone locks or the tab closes, the answer keeps arriving,
is saved, and is pushed to every other device of the owner as hub `thread` events (~1 s cadence), so
"Open on desktop" shows the same answer (§68). The final message is persisted before `done` is sent.

Gateway contract (lif/gateway/app.py): X-LIF-* headers arrive with the stream; the chunk carrying
`usage` also carries `lif` (alias, served_by, model, fallback, degraded, reason, route_decision). An
upstream 4xx comes back as HTTP 200 whose lines are raw JSON errors; a mid-stream failure is a
`data: {"error": …}` line with no [DONE]. A 429 of type capacity means the request waited 120 s for a
slot while BLERBZ had the GPU.

This module talks to the gateway with its own small httpx client (`_client`) because the shared
upstream.stream() helper yields lines only: Ask needs the response's X-LIF-* headers for the route, and the
error body's `type` (capacity vs rate_limit) to explain a 429. It calls exactly one path. The key never leaves
this process: not in errors, not in tech details, not in logs.

Privacy (brief §3): "Local only" sends X-LIF-Data-Class CONFIDENTIAL, so local/auto routes with built-in
rules; "Allow Jev routing" sends PUBLIC, which lets local/auto show the prompt to Jev to choose a
model. The answer is always generated by a local model.

Owner: AI.
"""
from __future__ import annotations

import asyncio
import json
import sqlite3
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import Any
from urllib.parse import quote

import httpx
from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse

from lif.common import log
from lif.console import auth, errors, humanize, intent, poller, settings, threads
from lif.console.contracts import (AiCapabilities, AskMode, Attachment, AttachmentIn, CommandRequest,
                                   CommandResolution, CreateThreadRequest, DecisionBadge, Fact, HumanError,
                                   HumanErrorAction, MessageRequest, ModeOption, OkResponse, PrivacyChoice,
                                   PrivacyOption, PrivacyUsed, Receipt, RouteStep, StreamDone, StreamRoute, TechDetail,
                                   Thread, ThreadEvent, ThreadSummary, TokenUsage, User)
from lif.console.errors import human
from lif.console.events import hub

LOG = log.get("lif.console.ai")

router = APIRouter(prefix="/api", tags=["ai"])     # spans areas: paths include /ai or /command

# ── vocabulary ────────────────────────────────────────────────────────────────────────────────

# Mode → (gateway alias, label, contextual help §96), from the one role table in humanize. Users pick
# capabilities, never physical models (§10).
MODES: dict[AskMode, tuple[str, str, str]] = {
    m: humanize.ROLE_BY_KEY[m][1:4] for m in ("auto", "fast", "balanced", "deep", "code", "vision")}  # type: ignore[misc]
DATA_CLASS: dict[PrivacyChoice, str] = {"local_only": "CONFIDENTIAL", "allow_jev": "PUBLIC"}

TEXT_KINDS = {"text", "code", "log", "markdown", "json", "csv", "document", "other"}
MAX_PROMPT_CHARS = 512 * 1024          # the gateway refuses bodies over 4 MiB; JSON escaping can double text
MAX_FILE_CHARS = 256 * 1024            # brief §1: ≤ 256 KB per file, extracted in the browser
MAX_FILES = 10
MAX_ATTACH_CHARS = 1024 * 1024
FLUSH_SEC = 1.0                        # partial-answer cadence for the DB and other devices
REQUEST_TIMEOUT = httpx.Timeout(300.0, connect=3.0)   # the gateway may queue up to 120 s, then stream

# Tests replace this with httpx.MockTransport; production uses the default network transport.
_transport: httpx.AsyncBaseTransport | None = None


def _client() -> httpx.AsyncClient:
    return httpx.AsyncClient(base_url=settings.gateway_url(), transport=_transport, timeout=REQUEST_TIMEOUT)


def _alias_label(alias: str) -> str:
    for r in poller.snapshot().roles:
        if r.alias == alias and r.label:
            return r.label
    return humanize.role_label(alias)


def friendly_model(profile: str | None) -> str | None:
    """Profile id → the name people see: the catalogue name if the poller knows it, else humanize's
    tidy version of the id ('qwen3-4b-instruct-2507-q4km-cpu' → 'Qwen3 4B Instruct 2507 (CPU)')."""
    if not profile:
        return None
    snap = poller.snapshot()
    for d in snap.deployments:
        if d.id == profile and d.name:
            return d.name
    for r in snap.roles:
        if r.served_by == profile and r.model_name:
            return r.model_name
    return humanize.model_name(profile) or profile


def model_device(profile: str | None) -> str | None:
    """Where a profile runs ('CPU' / 'GPU') as the registry or routing table records it; None when unknown —
    the receipt never guesses (§9 'Handled by … · GPU')."""
    if not profile:
        return None
    snap = poller.snapshot()
    dev = next((d.device for d in snap.deployments if d.id == profile and d.device), None)
    if dev is None:
        for src in (snap.raw.get("routing"), snap.raw.get("capabilities")):
            profs = src.get("profiles") if isinstance(src, dict) else None
            p = profs.get(profile) if isinstance(profs, dict) else None
            if isinstance(p, dict) and p.get("device"):
                dev = str(p["device"])
                break
    return dev.upper() if dev else None


def reason_label(reason: str | None, *, fallback: bool = False, degraded: bool = False) -> str | None:
    """Gateway reason (free text, router.py) → one human sentence (shared rules in humanize); raw stays in tech."""
    return humanize.role_cause(reason, fallback=fallback, degraded=degraded)[1] if reason else None


# ── capabilities ──────────────────────────────────────────────────────────────────────────────

@router.get("/ai/capabilities", response_model=AiCapabilities)
async def capabilities(user: User = Depends(auth.require("read"))) -> AiCapabilities:
    """Modes with one-line help and live availability from the poller (§10, §96). Unknown → available,
    because the gateway is the authority and will say why at request time."""
    snap = poller.snapshot()
    roles = {r.alias: r for r in snap.roles}
    modes = []
    for mode, (alias, label, blurb) in MODES.items():
        r = roles.get(alias)
        available, reason = True, None
        if mode == "auto":
            available = not roles or any(x.state not in ("offline",) for x in snap.roles if x.alias != "local/auto")
            reason = None if available else "No local model is answering right now."
        elif r is not None:
            if r.state == "offline" or r.cause == "not_deployed":
                available = False
                reason = (f"No local {label.lower()} model yet" if r.cause == "not_deployed"
                          else r.cause_label or f"The {label.lower()} model is unavailable right now")
            elif r.degraded or r.fallback_active:
                reason = r.cause_label or "Running on a backup model right now"
        modes.append(ModeOption(mode=mode, label=label, blurb=blurb, alias=alias, available=available, reason=reason))
    jev_ok = _jev_available(snap.raw)
    privacy = [
        PrivacyOption(value="local_only", label="Local only",
                      blurb="Your prompt never leaves this machine. Auto picks a model with built-in rules."),
        PrivacyOption(value="allow_jev", label="Allow Jev routing", available=jev_ok,
                      reason=None if jev_ok else "Jev is switched off or unreachable right now.",
                      blurb="Auto may show your prompt to Jev, an external decision service, to choose the "
                            "best local model. The answer is still written on this machine."),
    ]
    return AiCapabilities(modes=modes, privacy_options=privacy, external_allowed=False)


def _jev_available(raw: dict[str, Any]) -> bool:
    for src in ("health", "capabilities", "overview"):
        df = (raw.get(src) or {}).get("decision_fabric") if isinstance(raw.get(src), dict) else None
        if isinstance(df, dict) and "jev_enabled" in df:
            return bool(df.get("jev_enabled")) and not df.get("jev_breaker_open")
    return True


# ── threads ───────────────────────────────────────────────────────────────────────────────────

@contextmanager
def _storage() -> Iterator[None]:
    """Thread reads and writes: a locked or unwritable database is a human 503, not a generic 500."""
    try:
        yield
    except sqlite3.Error as e:
        raise errors.storage(e) from e


def _not_found() -> Exception:
    return human(404, "Conversation not found", "It may have been deleted on another device.",
                 "Start a new conversation from Ask.", [("Open Ask", "/ask")])


@router.get("/ai/threads", response_model=list[ThreadSummary])
async def list_threads(user: User = Depends(auth.require("read"))) -> list[ThreadSummary]:
    with _storage():
        return threads.list_threads(user.id)


@router.post("/ai/threads", response_model=Thread)
async def create_thread(req: CreateThreadRequest, user: User = Depends(auth.require("ask"))) -> Thread:
    with _storage():
        return threads.create_thread(user.id, req.mode, req.privacy, req.title, origin_device=user.device_name)


@router.get("/ai/threads/{thread_id}", response_model=Thread)
async def get_thread(thread_id: str, user: User = Depends(auth.require("read"))) -> Thread:
    with _storage():
        t = threads.get_thread(user.id, thread_id)
        if t is None:
            raise _not_found()
        stale = set(threads.stale_streaming(thread_id, set(_RUNS)))
        if stale:      # the console restarted mid-answer: say so instead of spinning forever
            err = HumanError(title="This answer was interrupted",
                             impact="Labzilla restarted while it was answering; the text so far is kept.",
                             next_step="Ask again to get a complete answer.",
                             actions=[HumanErrorAction(label="Retry", action="retry")])
            for m in t.messages:
                if m.id in stale:
                    threads.update_message(m.id, status="error", error=err)
                    m.status, m.error = "error", err
    return t


@router.delete("/ai/threads/{thread_id}", response_model=OkResponse)
async def delete_thread(thread_id: str, user: User = Depends(auth.require("ask"))) -> OkResponse:
    for run in [r for r in _RUNS.values() if r.thread_id == thread_id and r.user_id == user.id]:
        run.cancel()
    with _storage():
        deleted = threads.delete_thread(user.id, thread_id)
    if not deleted:
        raise _not_found()
    auth.audit(user, "ai.thread.delete", thread_id)
    return OkResponse(message="Conversation deleted")


# ── attachments (§20) ─────────────────────────────────────────────────────────────────────────

def _attachments(items: list[AttachmentIn]) -> list[dict[str, Any]]:
    """Decide per file what the model will see. Text is inlined under a header; images and PDFs are not
    sent anywhere (no local vision model, no server-side PDF extraction) and say so."""
    vision = next((r for r in poller.snapshot().roles if r.alias == "local/vision"), None)
    out: list[dict[str, Any]] = []
    budget = MAX_ATTACH_CHARS
    for i, a in enumerate(items):
        meta = Attachment(name=a.name[:200], kind=a.kind, size=max(0, a.size)).model_dump()
        if i >= MAX_FILES:
            meta["note"] = f"Skipped: up to {MAX_FILES} files per message."
        elif a.kind == "image":
            meta["note"] = ("No local vision model yet — the image was not read." if vision is None or
                            vision.cause == "not_deployed" or vision.state == "offline" else
                            "Images can't be sent from Ask yet — the image was not read.")
        elif a.kind == "pdf":
            meta["note"] = "PDF text extraction isn't available yet — paste the text you need instead."
        elif a.kind in TEXT_KINDS and a.text:
            text = a.text[:MAX_FILE_CHARS]
            if len(text) > budget:
                meta["note"] = "Skipped: the message would be too large for the model."
            else:
                budget -= len(text)
                meta.update(included=True, text=text, note="Processed locally" + (
                    f"; only the first {MAX_FILE_CHARS // 1024} KB was used." if len(a.text) > MAX_FILE_CHARS else "."))
        else:
            meta["note"] = "This file type can't be read yet."
        out.append(meta)
    return out


# ── streaming ─────────────────────────────────────────────────────────────────────────────────

@dataclass
class _Run:
    """One answer being produced. Lives until the gateway finishes, independent of the browser."""
    thread_id: str
    message_id: str
    user_id: str
    queue: asyncio.Queue[tuple[str, dict[str, Any]] | None] = field(default_factory=asyncio.Queue)
    attached: bool = True
    task: asyncio.Task[None] | None = None
    text: list[str] = field(default_factory=list)
    flushed_at: float = 0.0

    def emit(self, event: str, data: dict[str, Any]) -> None:
        if self.attached:
            self.queue.put_nowait((event, data))

    def cancel(self) -> None:
        if self.task is not None and not self.task.done():
            self.task.cancel()
            # A task cancelled before its first step never enters produce()'s try block; settle it here.
            self.task.add_done_callback(lambda _: _finish(self, "cancelled", None, None)
                                        if self.message_id in _RUNS else None)

    @property
    def content(self) -> str:
        return "".join(self.text)


_RUNS: dict[str, _Run] = {}         # message id → run; also the strong reference that keeps the task alive


@dataclass
class _Outcome:
    """What the gateway told us, accumulated while streaming."""
    headers: dict[str, str] = field(default_factory=dict)
    meta: dict[str, Any] = field(default_factory=dict)
    usage: dict[str, Any] = field(default_factory=dict)
    finish: str | None = None
    first_token_ms: float | None = None


def _err(title: str, impact: str, next_step: str, actions: list[tuple[str, str]] | None = None,
         **tech: Any) -> HumanError:
    return HumanError(title=title, impact=impact, next_step=next_step,
                      actions=[HumanErrorAction(label=lbl, action=act) for lbl, act in actions or []],
                      tech=[TechDetail(label=k, value=str(v)[:300]) for k, v in tech.items() if v not in (None, "")])


def gateway_error(status: int, raw: bytes | str, alias: str) -> HumanError:
    """A gateway refusal → what failed, what it means, what to do (§81). Never 'HTTP 503'."""
    text = raw.decode("utf-8", "replace") if isinstance(raw, bytes) else raw
    msg, typ = text.strip()[:300], ""
    try:
        body = json.loads(text)
        e = body.get("error") if isinstance(body, dict) else None
        if isinstance(e, dict):
            msg, typ = str(e.get("message") or ""), str(e.get("type") or "")
        elif isinstance(e, str):
            msg = e
    except (ValueError, AttributeError):
        pass
    label, low = humanize.role_label(alias), msg.lower()
    tech = {"status": status, "type": typ, "message": msg, "alias": alias}
    if status == 429 and typ == "capacity":
        primary = "primary-workload" in low
        cause = ("BLERBZ is using the GPU, so local AI answers one request at a time"
                 if primary else "Every local model slot stayed busy")
        return _err("Waiting for the primary workload to finish" if primary else "Local AI is busy",
                    f"{cause}, and your request waited 2 minutes without getting a turn. Nothing was lost.",
                    "Retry in a minute — Labzilla gives capacity back to local AI automatically.",
                    [("Retry", "retry")], **tech)
    if status == 429:
        return _err("Too many requests from the console", "The AI gateway is slowing the console down for a moment.",
                    "Wait a few seconds and retry.", [("Retry", "retry")], **tech)
    if status in (401, 403):
        return _err("Ask isn't connected to the AI gateway", "The gateway did not accept the console's key.",
                    "The owner needs to roll out the gateway after the console's key was added.", [], **tech)
    if status == 413:
        return _err("That's too much text for one request", "The message and its files are over the gateway's limit.",
                    "Send a shorter message or fewer files.", [], **tech)
    if status == 503 and "no local model is deployed" in low:
        if alias == "local/vision":
            return _err("No local vision model yet", "Labzilla can't read images on this machine yet — "
                        "local/vision is not deployed.", "Choose another mode, or describe the image in text.",
                        [("Open Models", "/models")], **tech)
        return _err(f"No local {label} model yet", f"Nothing is deployed for the {label} mode on this machine.",
                    "Choose Auto or another mode.", [("Open Models", "/models")], **tech)
    if status == 503 and "are unavailable" in low:
        return _err(f"{label} models are offline", f"Every model that can answer in {label} mode is down right now.",
                    "Try Auto or Fast, or check Models for what's happening.",
                    [("Retry", "retry"), ("Open Models", "/models")], **tech)
    if status == 503:
        return _err("No model can answer right now", "Local AI has no free model for this request.",
                    "Retry in a moment.", [("Retry", "retry")], **tech)
    if 400 <= status < 500:
        return _err("The model couldn't accept this request", "The local model refused the request as sent.",
                    "Try rephrasing, or remove large files.", [("Retry", "retry")], **tech)
    return _err("Local AI couldn't answer", "The AI gateway reported an error.", "Retry in a moment.",
                [("Retry", "retry")], **tech)


def _unreachable(detail: str) -> HumanError:
    return _err("Local AI is unreachable", "The AI gateway didn't answer, so nothing was generated.",
                "Retry in a moment; if it keeps happening, check System → Services.",
                [("Retry", "retry"), ("Open Services", "/system/services")], error=detail)


def _midstream(detail: str) -> HumanError:
    return _err("The model stopped mid-answer", "The text so far is kept, but it may be incomplete.",
                "Retry to get a complete answer.", [("Retry", "retry")], error=detail)


def _true(v: str | None) -> bool:
    return (v or "").lower() == "true"


def _trail(mode: AskMode, alias: str, decision: dict[str, Any] | None) -> list[RouteStep]:
    """'Auto ↓ Jev ↓ Local Fast' (§11): the mode, who decided (only when Jev did), the role that answered."""
    steps = [RouteStep(label=MODES[mode][1], kind="mode")]
    if decision and decision.get("provider") == "jev":
        steps.append(RouteStep(label="Jev", kind="decision"))
    if alias and alias != "local/auto":
        steps.append(RouteStep(label=f"Local {_alias_label(alias)}", kind="model"))
    return steps


def _decision_badge(d: dict[str, Any], alias: str, privacy: PrivacyChoice) -> DecisionBadge:
    """The local/auto route decision as a badge (§25): outcome, confidence and structured why — never reasoning."""
    provider, action = str(d.get("provider") or ""), str(d.get("action") or "")
    acted = action in ("auto", "validate")
    label = _alias_label(alias).lower()
    sentence = (f"Use the {label} local model" if acted else
                f"Not sure which model fits; used the {label} model")
    by = {"jev": "jev", "rules": "rules", "local_llm": "local_model"}.get(provider, "code")
    why = [Fact(label="Request looks like", value=str(d.get("decision") or "unknown")),
           Fact(label="Decided by", value={"jev": "Jev (fast decision model)", "rules": "Built-in rules",
                                           "local_llm": "Local model"}.get(provider, "Default choice")),
           Fact(label="Confidence", value={"auto": "High", "validate": "Good enough to act"}.get(action, "Too low to act on")),
           Fact(label="Prompt shared with Jev", value="Yes" if provider == "jev" and privacy == "allow_jev" else "No")]
    conf = d.get("confidence")
    return DecisionBadge(decision=sentence, confidence=float(conf) if isinstance(conf, (int, float)) else None,
                         decided_by=by, actionable=acted, why=why)  # type: ignore[arg-type]


def build_receipt(o: _Outcome, mode: AskMode, requested: str, privacy: PrivacyChoice, latency_ms: float,
                  clamp_possible: bool, message_id: str) -> Receipt:
    """Gateway headers + the final `lif` meta → 'Handled by …' (§9) with the route and privacy used (§11, §64)."""
    h, m = o.headers, o.meta
    alias = str(m.get("alias") or (requested if requested != "local/auto" else h.get("x-lif-requested") or requested))
    served = str(m.get("served_by") or h.get("x-lif-served-by") or "") or None
    reason = str(m.get("reason") or h.get("x-lif-reason") or "") or None
    decision = m.get("route_decision") if isinstance(m.get("route_decision"), dict) else None
    # The gateway sets fallback=true whenever local/auto resolves to another alias; that is routing, not a
    # fallback. A real fallback is a later model in the chain (reason 'primary unavailable…').
    fallback = bool(reason and reason.lower().startswith(("primary unavailable", "upstream_error"))) or (
        requested != "local/auto" and (bool(m.get("fallback")) or _true(h.get("x-lif-fallback"))))
    degraded = bool(m.get("degraded")) or _true(h.get("x-lif-degraded"))
    used: PrivacyUsed = "local_jev" if decision and decision.get("provider") == "jev" and privacy == "allow_jev" \
        else "local_only"
    usage = o.usage
    tech = {"requested alias": requested, "served by (profile)": served, "device": model_device(served),
            "model revision": m.get("model"),
            "gateway reason": reason, "route decision": json.dumps(decision) if decision else None,
            "data class sent": DATA_CLASS[privacy], "finish reason": o.finish,
            "time to first token": f"{o.first_token_ms:.0f} ms" if o.first_token_ms is not None else None,
            "cache": m.get("cache"), "canary": "yes" if m.get("canary") else None}
    return Receipt(alias=alias, role_label=_alias_label(alias), served_by=served, model_name=friendly_model(served),
                   physical_model=str(m["model"]) if m.get("model") else None, fallback=fallback, degraded=degraded,
                   reason_label=reason_label(reason, fallback=fallback, degraded=degraded),
                   latency_ms=round(latency_ms, 1), privacy=used, route=_trail(mode, alias, decision),
                   decision=_decision_badge(decision, alias, privacy) if decision else None, request_id=message_id,
                   tokens=TokenUsage(prompt=int(usage.get("prompt_tokens") or 0),
                                     completion=int(usage.get("completion_tokens") or 0)) if usage else None,
                   clamped=clamp_possible and o.finish == "length",
                   tech=[TechDetail(label=k, value=str(v)) for k, v in tech.items() if v not in (None, "")])


def parse_line(line: str) -> tuple[str, Any]:
    """One gateway stream line → ('chunk', dict) | ('error', dict|str) | ('done', None) | ('skip', None).

    Handles the three shapes the gateway emits: OpenAI `data:` chunks, an in-band `data: {"error":…}`
    after a mid-stream failure, and raw upstream JSON error lines inside a 200 (upstream 4xx)."""
    s = line.strip()
    if not s or s.startswith(":") or s.startswith("event:"):
        return "skip", None
    if s.startswith("data:"):
        payload = s[5:].strip()
        if payload == "[DONE]":
            return "done", None
    elif s.startswith("{"):
        payload = s
    else:
        return "skip", None
    try:
        obj = json.loads(payload)
    except ValueError:
        return "skip", None
    if not isinstance(obj, dict):
        return "skip", None
    if "error" in obj:
        return "error", obj["error"]
    return "chunk", obj


def _thread_event(run: _Run, status: str) -> None:
    hub.publish("thread", ThreadEvent(thread_id=run.thread_id, message_id=run.message_id, content=run.content,
                                      status=status), audience=f"user:{run.user_id}")  # type: ignore[arg-type]


def _flush(run: _Run, force: bool = False) -> None:
    now = time.monotonic()
    if force or now - run.flushed_at >= FLUSH_SEC:
        run.flushed_at = now
        threads.update_message(run.message_id, content=run.content)
        _thread_event(run, "streaming")


def _gpu_imminent() -> bool:
    """Is the gateway clamping answers right now? It caps max_tokens at 512 only while gpusched says IMMINENT
    (production running, residents reloading, or gpusched not visible) and never reports it per response."""
    raw = poller.snapshot().raw
    gpu = raw.get("gpu") if isinstance(raw.get("gpu"), dict) else {}
    health = raw.get("health") if isinstance(raw.get("health"), dict) else {}
    state = gpu.get("state") or (health.get("blerbz") or {}).get("state")
    return str(state or "").upper() == "IMMINENT"


async def produce(run: _Run, body: dict[str, Any], *, mode: AskMode, privacy: PrivacyChoice) -> None:
    """Consume the gateway stream to the end, persist the answer, then tell the browser (if still there)."""
    requested = body["model"]
    o = _Outcome()
    status, error, receipt = "done", None, None
    clamp_possible = _gpu_imminent()
    t0 = time.perf_counter()
    try:
        key = settings.gateway_key()
        if not key:
            raise _NotConfigured()
        headers = {"Authorization": f"Bearer {key}", "X-LIF-Data-Class": DATA_CLASS[privacy],
                   "X-LIF-Workload": "console", "Accept": "text/event-stream"}
        async with _client() as c, c.stream("POST", "/v1/chat/completions", json=body, headers=headers) as resp:
            if resp.status_code >= 400:
                status, error = "error", gateway_error(resp.status_code, await resp.aread(), requested)
            else:
                o.headers = {k.lower(): v for k, v in resp.headers.items() if k.lower().startswith("x-lif-")}
                served = o.headers.get("x-lif-served-by")
                early = _trail(mode, requested, None)
                if requested == "local/auto" and served:
                    early.append(RouteStep(label=friendly_model(served) or served, kind="model"))
                run.emit("route", StreamRoute(route=early, privacy="local_only",
                                              message_id=run.message_id).model_dump())
                async for line in resp.aiter_lines():
                    kind, val = parse_line(line)
                    if kind == "done":
                        break
                    if kind == "error":
                        etype = val.get("type") if isinstance(val, dict) else ""
                        detail = json.dumps(val)[:300]
                        status, error = "error", (_midstream(detail) if run.text or etype == "upstream" else
                                                  gateway_error(400, json.dumps({"error": val}), requested))
                        break
                    if kind != "chunk":
                        continue
                    for ch in val.get("choices") or []:
                        delta = (ch.get("delta") or {}).get("content") or ch.get("text") or ""
                        if delta:
                            if o.first_token_ms is None:
                                o.first_token_ms = (time.perf_counter() - t0) * 1000
                            run.text.append(delta)
                            run.emit("delta", {"text": delta})
                        if ch.get("finish_reason"):
                            o.finish = ch["finish_reason"]
                    if val.get("usage"):
                        o.usage = val["usage"]
                    if isinstance(val.get("lif"), dict):
                        o.meta = val["lif"]
                    if run.text:
                        _flush(run)
                if status == "done":
                    receipt = build_receipt(o, mode, requested, privacy, (time.perf_counter() - t0) * 1000,
                                            clamp_possible, run.message_id)
    except asyncio.CancelledError:
        status = "cancelled"
    except _NotConfigured:
        status, error = "error", _err("Ask isn't set up yet", "The console has no key for the AI gateway, so it "
                                      "can't send prompts.", "The owner needs to create the console's gateway key "
                                      "(scripts/create-secrets.sh) and roll out the console and gateway.")
    except httpx.HTTPError as e:
        status = "error"
        error = _midstream(type(e).__name__) if run.text else _unreachable(type(e).__name__)
    except Exception as e:              # never leave a message spinning; the crash is logged, not shown raw
        log.event(LOG, "ask_failed", error=type(e).__name__)
        status, error = "error", _err("Something went wrong while answering", "The answer didn't complete.",
                                      "Retry; if it keeps happening, check System → Logs.", [("Retry", "retry")],
                                      error=type(e).__name__)
    finally:
        _finish(run, status, error, receipt)


class _NotConfigured(Exception):
    pass


def _finish(run: _Run, status: str, error: HumanError | None, receipt: Receipt | None) -> None:
    """Persist first, then notify: 'Open on desktop' must find the finished answer the moment `done` lands."""
    try:
        threads.update_message(run.message_id, content=run.content, status=status, error=error, receipt=receipt)
    except Exception as e:              # storage down: the browser still gets the answer it watched stream
        log.event(LOG, "ask_persist_failed", error=type(e).__name__)
    if receipt is not None:
        run.emit("receipt", receipt.model_dump())
    if error is not None:
        run.emit("error", error.model_dump())
    run.emit("done", StreamDone(message_id=run.message_id).model_dump())
    if run.attached:
        run.queue.put_nowait(None)
    _thread_event(run, status)
    _RUNS.pop(run.message_id, None)
    log.event(LOG, "ask_done", thread=run.thread_id, message=run.message_id, status=status,
              chars=len(run.content), alias=receipt.alias if receipt else None)


async def _relay(run: _Run):
    """The browser's view of a run. Leaving (disconnect, navigation) detaches it; the run carries on."""
    try:
        while True:
            item = await run.queue.get()
            if item is None:
                return
            event, data = item
            yield f"event: {event}\ndata: {json.dumps(data, separators=(',', ':'))}\n\n"
    finally:
        run.attached = False


def _too_long() -> errors.HumanHTTPError:
    mb = threads.THREAD_QUOTA_BYTES // (1024 * 1024)
    return human(413, "This conversation is too long", "Nothing was sent: a conversation keeps at most "
                 f"{mb} MB of messages.", "Copy your message, then start a new conversation and paste it there.",
                 [("New conversation", "/ask")], {"limit_bytes": threads.THREAD_QUOTA_BYTES})


@router.post("/ai/threads/{thread_id}/messages")
async def send_message(thread_id: str, req: MessageRequest, request: Request,
                       user: User = Depends(auth.require("ask"))) -> StreamingResponse:
    if not getattr(request.state, "ask_rate_checked", False):     # app.Guard counts it before reading the body
        sess = auth.session_of(request)
        auth.check_rate(auth.limiters(request).ask, f"s:{sess.token_hash}" if sess else user.id, "ask")
    # The parsed body stays referenced by the request for as long as the answer streams; the prompt is
    # copied below, so drop the raw bytes and JSON now (up to 4 MB each per running answer).
    for cached in ("_body", "_json"):
        request.__dict__.pop(cached, None)
    with _storage():
        t = threads.get_thread(user.id, thread_id)
    if t is None:
        raise _not_found()
    content = req.content.strip()
    if len(content) > MAX_PROMPT_CHARS:
        raise human(422, "That message is too long", "Nothing was sent.",
                    f"Keep the message under {MAX_PROMPT_CHARS // 1024} KB, or attach the text as a file.")
    atts = _attachments(req.attachments)
    if not content and not any(a.get("included") for a in atts):
        raise human(422, "Type a prompt first", "Nothing was sent.",
                    "Write what you want to know, or attach a text file." if not atts else
                    "None of the attached files could be read here; add a few words or a text file.")
    alias = MODES[req.mode][0]
    # File text never goes to Jev: Jev routing sees the last user message, which carries the files.
    # With files included the request is sent as Local only, whatever the toggle says.
    privacy: PrivacyChoice = req.privacy
    if privacy == "allow_jev" and any(a.get("included") for a in atts):
        privacy = "local_only"
        for a in atts:
            if a.get("included"):
                a["note"] = str(a.get("note") or "").replace("Processed locally", "Processed locally (messages "
                                                                 "with files never go to Jev)", 1)
    prompt = threads.compose(content, atts)
    untitled = not t.messages and t.title == threads.title_from("")    # keep a title the user chose
    with _storage():
        if threads.thread_bytes(thread_id) + len(content.encode()) > threads.THREAD_QUOTA_BYTES:
            raise _too_long()
        history = threads.context(thread_id, before=time.time())
        _, answer = threads.start_turn(thread_id, content, atts, mode=req.mode, privacy=req.privacy,
                                       title=threads.title_from(content or atts[0]["name"]) if untitled else None)
    try:                    # best effort: the turn is already stored and must get its answer
        gone = threads.enforce_quota(user.id, keep=thread_id)
    except sqlite3.Error as exc:
        gone = []
        log.event(LOG, "thread_quota_failed", error=type(exc).__name__)
    if gone:
        log.event(LOG, "thread_quota_pruned", threads=len(gone))
    auth.audit(user, "ai.ask", thread_id, {"mode": req.mode, "privacy": privacy, "chars": len(prompt),
                                           "files": len(atts)})
    body = {"model": alias, "stream": True, "messages": [*history, {"role": "user", "content": prompt}]}
    run = _Run(thread_id=thread_id, message_id=answer.id, user_id=user.id)
    run.emit("route", StreamRoute(route=_trail(req.mode, alias, None), privacy="local_only",
                                  message_id=answer.id).model_dump())
    _RUNS[answer.id] = run
    _thread_event(run, "streaming")
    run.task = asyncio.create_task(produce(run, body, mode=req.mode, privacy=privacy))
    return StreamingResponse(_relay(run), media_type="text/event-stream",
                             headers={"Cache-Control": "no-store", "X-Accel-Buffering": "no"})


@router.post("/ai/threads/{thread_id}/messages/{message_id}/cancel", response_model=OkResponse)
async def cancel_message(thread_id: str, message_id: str, user: User = Depends(auth.require("ask"))) -> OkResponse:
    with _storage():
        known = threads.get_thread(user.id, thread_id) is not None
    if not known:
        raise _not_found()
    run = _RUNS.get(message_id)
    if run is not None and run.thread_id == thread_id:
        run.cancel()
        return OkResponse(message="Stopped")
    row = threads.message_row(thread_id, message_id)
    if row is None:
        raise human(404, "Answer not found", "It may have been deleted.", "Refresh the conversation.")
    if row["status"] == "streaming":      # orphaned by a restart: settle it
        threads.update_message(message_id, status="cancelled")
        return OkResponse(message="Stopped")
    return OkResponse(message="This answer had already finished")


# ── command bar (§7, §8) ──────────────────────────────────────────────────────────────────────

@router.post("/command", response_model=CommandResolution)
async def command(req: CommandRequest, user: User = Depends(auth.require("read"))) -> CommandResolution:
    """Deterministic resolution; never executes anything (operational commands come back as a ProposedAction)."""
    text = req.text.strip()
    if not text:
        raise human(422, "Type a command or a question", "Nothing was run.", "Try “Why is the GPU busy?”.")
    if len(text) > 4000:
        raise human(422, "That's too long for the command bar", "Nothing was run.", "Use Ask for long prompts.",
                    [("Open Ask", "/ask")])
    out = intent.resolve(text, poller.snapshot(), user)
    if out.kind == "knowledge_query":
        await _knowledge_preview(out, text)
    log.event(LOG, "command", kind=out.kind, confidence=out.confidence, chars=len(text))
    return out


async def _knowledge_preview(out: CommandResolution, text: str) -> None:
    """Show the best few knowledge matches inline; the full search stays one tap away (navigate)."""
    from lif.console.routes import knowledge   # sibling route module; imported late to keep startup light

    try:
        hits = await knowledge.search_hits(text, limit=3)
    except Exception as e:              # knowledge down or not bundled: the navigate link still works
        log.event(LOG, "command_knowledge_failed", error=type(e).__name__)
        return
    if not hits:
        out.answer = "No matching decisions, evidence or assumptions were found. Open Knowledge to search differently."
        return
    best = hits[0]
    out.answer = f"**{best.title}**" + (f" — {best.summary}" if best.summary else "")
    out.facts = [Fact(label=h.type.capitalize() or "Item", value=h.title) for h in hits]
    out.navigate = f"/knowledge/o/{quote(best.key, safe='')}" if len(hits) == 1 else out.navigate
